web:
  build: .
  command: 'bash -c ''node index.js'''
  working_dir: /app/user
  environment:
    PORT: 8080
    REDIS_URL: 'redis://herokuRedis:6379'
  ports:
    - '8080:8080'
  links:
    - herokuRedis
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 8080
    REDIS_URL: 'redis://herokuRedis:6379'
  ports:
    - '8080:8080'
  links:
    - herokuRedis
  volumes:
    - '.:/app/user'
herokuRedis:
  image: redis
